/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Brayan
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        btn_trabajador = new javax.swing.JButton();
        btn_labores = new javax.swing.JButton();
        btn_Lotes = new javax.swing.JButton();
        btncintaje = new javax.swing.JButton();
        btn_cosechas = new javax.swing.JButton();
        btn_asignar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        administador = new javax.swing.JMenuItem();
        edad = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        lista_cin = new javax.swing.JMenuItem();
        lista_tra = new javax.swing.JMenuItem();
        admin = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono.png"))); // NOI18N

        btn_trabajador.setText(".......");
        btn_trabajador.setAlignmentY(0.0F);
        btn_trabajador.setAutoscrolls(true);
        btn_trabajador.setMargin(new java.awt.Insets(1, 8, 1, 8));
        btn_trabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_trabajadorActionPerformed(evt);
            }
        });

        btn_labores.setText("Labores");
        btn_labores.setAlignmentY(0.0F);
        btn_labores.setAutoscrolls(true);
        btn_labores.setMargin(new java.awt.Insets(1, 8, 1, 8));
        btn_labores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_laboresActionPerformed(evt);
            }
        });

        btn_Lotes.setText("Lotes");
        btn_Lotes.setAlignmentY(0.0F);
        btn_Lotes.setAutoscrolls(true);
        btn_Lotes.setMargin(new java.awt.Insets(1, 8, 1, 8));
        btn_Lotes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LotesActionPerformed(evt);
            }
        });

        btncintaje.setText("Cintaje");
        btncintaje.setAlignmentY(0.0F);
        btncintaje.setAutoscrolls(true);
        btncintaje.setMargin(new java.awt.Insets(1, 8, 1, 8));
        btncintaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncintajeActionPerformed(evt);
            }
        });

        btn_cosechas.setText("Cosechas");
        btn_cosechas.setAlignmentY(0.0F);
        btn_cosechas.setAutoscrolls(true);
        btn_cosechas.setMargin(new java.awt.Insets(1, 8, 1, 8));
        btn_cosechas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cosechasActionPerformed(evt);
            }
        });

        btn_asignar.setText("Asignar labores");
        btn_asignar.setAlignmentY(0.0F);
        btn_asignar.setAutoscrolls(true);
        btn_asignar.setMargin(new java.awt.Insets(1, 8, 1, 8));
        btn_asignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_asignarActionPerformed(evt);
            }
        });

        fondo.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        fondo.setLayer(btn_trabajador, javax.swing.JLayeredPane.DEFAULT_LAYER);
        fondo.setLayer(btn_labores, javax.swing.JLayeredPane.DEFAULT_LAYER);
        fondo.setLayer(btn_Lotes, javax.swing.JLayeredPane.DEFAULT_LAYER);
        fondo.setLayer(btncintaje, javax.swing.JLayeredPane.DEFAULT_LAYER);
        fondo.setLayer(btn_cosechas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        fondo.setLayer(btn_asignar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addContainerGap(280, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                .addGap(278, 278, 278))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoLayout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btncintaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_asignar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_trabajador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_labores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Lotes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_cosechas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(221, 221, 221))
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addComponent(btncintaje)
                        .addGap(18, 18, 18)
                        .addComponent(btn_asignar))
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addComponent(btn_trabajador)
                        .addGap(18, 18, 18)
                        .addComponent(btn_labores))
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addComponent(btn_Lotes)
                        .addGap(18, 18, 18)
                        .addComponent(btn_cosechas)))
                .addGap(134, 134, 134))
        );

        jMenu1.setText("Archivos");

        administador.setText("Administradores");
        administador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                administadorActionPerformed(evt);
            }
        });
        jMenu1.add(administador);

        jMenuBar1.add(jMenu1);

        edad.setText("Lista");
        edad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edadActionPerformed(evt);
            }
        });

        jMenuItem2.setText("Trabajadores");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        edad.add(jMenuItem2);

        lista_cin.setText("Edad fruta");
        lista_cin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lista_cinActionPerformed(evt);
            }
        });
        edad.add(lista_cin);

        lista_tra.setText("Cosechas");
        lista_tra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lista_traActionPerformed(evt);
            }
        });
        edad.add(lista_tra);

        admin.setText("Administradores");
        admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminActionPerformed(evt);
            }
        });
        edad.add(admin);

        jMenuBar1.add(edad);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_trabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_trabajadorActionPerformed
    Trabajadores tra=new Trabajadores();
    fondo.add(tra);
    tra.show();
     
     
    }//GEN-LAST:event_btn_trabajadorActionPerformed

    private void btn_LotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LotesActionPerformed
    Lotes lot =new Lotes();
      fondo.add(lot);
      lot.show();
    }//GEN-LAST:event_btn_LotesActionPerformed

    private void btn_asignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_asignarActionPerformed
       Asignacion asig=new Asignacion();
        fondo.add(asig);
     asig.show();
     
    }//GEN-LAST:event_btn_asignarActionPerformed

    private void btncintajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncintajeActionPerformed
      Cintaje cin=new Cintaje();
      fondo.add(cin);
      cin.show();
    }//GEN-LAST:event_btncintajeActionPerformed

    private void btn_laboresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_laboresActionPerformed
       Labores lab=new Labores();
       fondo.add(lab);
       lab.show();
    }//GEN-LAST:event_btn_laboresActionPerformed

    private void btn_cosechasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cosechasActionPerformed
      Cosechas cose=new Cosechas();
      fondo.add(cose);
      cose.show();
    }//GEN-LAST:event_btn_cosechasActionPerformed

    private void lista_cinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lista_cinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lista_cinActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
      Lista_Trabajadores lt=new Lista_Trabajadores();
      fondo.add(lt);
      lt.show();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void edadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edadActionPerformed
      Lista_Cintaje lc =new Lista_Cintaje();
       fondo.add(lc);
      lc.show();
    }//GEN-LAST:event_edadActionPerformed

    private void lista_traActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lista_traActionPerformed
      Lista_Cosechas lco=new Lista_Cosechas();
       fondo.add(lco);
      lco.show();
    }//GEN-LAST:event_lista_traActionPerformed

    private void administadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_administadorActionPerformed
      Administradores admin=new Administradores();
       fondo.add(admin);
      admin.show();
    }//GEN-LAST:event_administadorActionPerformed

    private void adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminActionPerformed
    Lista_administradores lad=new Lista_administradores();
     fondo.add(lad);
      lad.show();
    }//GEN-LAST:event_adminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem admin;
    private javax.swing.JMenuItem administador;
    private javax.swing.JButton btn_Lotes;
    private javax.swing.JButton btn_asignar;
    private javax.swing.JButton btn_cosechas;
    private javax.swing.JButton btn_labores;
    private javax.swing.JButton btn_trabajador;
    private javax.swing.JButton btncintaje;
    private javax.swing.JMenu edad;
    private javax.swing.JDesktopPane fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem lista_cin;
    private javax.swing.JMenuItem lista_tra;
    // End of variables declaration//GEN-END:variables
}
